services:
  db:
    image: postgres:latest
    restart: always
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql:z
    environment:
      - POSTGRES_DB=messenger
      - POSTGRES_PASSWORD=notasecretanymore
    expose:
      - 5432
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
  backend:
    build:
      context: .
      dockerfile: rest-backend/Dockerfile
      target: final
    expose:
      - 3000
    environment:
      - PG_DBNAME=messenger
      - PG_HOST=db
      - PG_USER=postgres
      - PG_PASSWORD=notasecretanymore
      - ADDRESS=0.0.0.0:3000
      - RUST_LOG=debug
      - BROKER_HOST=broker:4000
      - ENC_SECRET=cryptographicallysecure
      - COMMS_SECRET=internalcommssecret
    depends_on:
      db:
        condition: service_healthy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`api.localhost`)"
      - "traefik.http.routers.backend.entrypoints=web"
      - "traefik.http.services.backend.loadbalancer.server.port=3000"
  broker:
    build:
      context: .
      dockerfile: broker/Dockerfile
      target: final
    expose:
      - 4000
    environment:
      - WS_ADDRESS=0.0.0.0:8080
      - API_COMMS_ADDRESS=0.0.0.0:4000
      - API_HOST=backend:3000
      - RUST_LOG=debug
      - COMMS_SECRET=internalcommssecret
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.broker.rule=Host(`ws.localhost`)"
      - "traefik.http.routers.broker.entrypoints=web"
      - "traefik.http.services.broker.loadbalancer.server.port=8080"
      - "traefik.http.services.broker.loadbalancer.responseForwarding.flushInterval=100ms"
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      target: final
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`localhost`)"
      - "traefik.http.routers.frontend.entrypoints=web"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"
  traefik:
    image: traefik:v3.7
    security_opt:
      - label=disable
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
      - "--providers.docker.exposedByDefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - ${DOCKER_SOCK_PATH:-/var/run/docker.sock}:/var/run/docker.sock:ro
volumes:
  db-data:
